# Generated by Django 4.2.18 on 2025-02-15 15:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='profile_pics/default', max_length=255, verbose_name='image'),
        ),
    ]
