# Generated by Django 4.2.18 on 2025-01-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
