# Generated by Django 4.2.18 on 2025-02-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(default='No comment provided'),
            preserve_default=False,
        ),
    ]
