# Generated by Django 4.2.18 on 2025-01-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='special_request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
